default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["MYSQL_USERNAME"] || "myuser" %>
  password: <%= ENV["MYSQL_PASSWORD"] || "mypassword" %>
  host: <%= ENV["MYSQL_HOST2"] || "mydb" %>
  # socket: /tmp/mysql.sock

development:
  <<: *default
  database: backend_development

test:
  <<: *default
  database: backend_test

production:
  <<: *default
  database: backend_production
