default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["MYSQL_USERNAME"] || "myuser" %>
  password: <%= ENV["MYSQL_PASSWORD"] || "mypassword" %>
  host: <%= ENV["MYSQL_HOST2"] || "mydb" %>

development:
  <<: *default
  database: backend_development

test:
  # <<: *default
  database: <%= ENV['MYSQL_DATABASE'] || 'backend_test' %> #MYSQL_DATABASEはGithub Actionsで設定されている


production:
  <<: *default
  database: backend_production
