default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: backend_development
  host: <%= ENV["MYSQL_HOST_ECS"] || "mydb" %>
  username: <%= ENV["MYSQL_USERNAME_LOCAL"] %>
  password: <%= ENV["MYSQL_PASSWORD_LOCAL"] %>

test:
  <<: *default
  database: backend_test
  host: <%= ENV["MYSQL_HOST_ECS"] || "mydb" %>
  username: <%= ENV["MYSQL_USERNAME_LOCAL"] %>
  password: <%= ENV["MYSQL_PASSWORD_LOCAL"] %>

production:
  <<: *default
